version: '3.2'

services:
  mariadb42:
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    build:
      context: mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    expose:
      - "3306"

  nginx42:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress42
    build:
      context: nginx
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    ports:
      - "443:443"

  wordpress42:
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb42
    build:
      context: wordpress
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/hrecolet/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/hrecolet/data/mariadb'

networks:
  inception:
    driver: bridge